_pimcore:
    resource: "@PimcoreCoreBundle/config/routing.yaml"

app:
    resource: "../src/Controller/"
    type: attribute

ayra_bundle:
    resource: "../bundles/ayra-bundle/src/Controller/"
    type: attribute

sso_login_bundle:
    resource: "../bundles/SSOLoginBundle/src/Controller/"
    type: attribute